apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1u8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1u8s
    app.kubernetes.io/part-of: cin4s-839-0029-app
  name: devfile-sample-1u8s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1u8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1u8s
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0029-tenant/cin4s-839-0029-app/devfile-sample-1u8s@sha256:9cec3dc6930a6f5f5244711b25c9283912132bc04f7cf4bfae4565b8b34f30d9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
